# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def generate_version()
  package = load_json(json_path: '../package.json')
  app_version = package['version']
  build_number = DateTime.now.strftime('%Y%m%d%H%M')
  Hash[
    'app_version' => app_version,
    'build_number' => build_number
  ]
end

platform :ios do
  desc "Build a new beta release of the app."
  lane :beta do
    version_info = generate_version()
    set_info_plist_value(
      path: "Connect/Info.plist",
      key: 'CFBundleShortVersionString',
      value: version_info['app_version']
    )
    set_info_plist_value(
      path: "Connect/Info.plist",
      key: 'CFBundleVersion',
      value: version_info['build_number']
    )
    set_info_plist_value(
      path: "ConnectTests/Info.plist",
      key: 'CFBundleShortVersionString',
      value: version_info['app_version']
    )
    set_info_plist_value(
      path: "ConnectTests/Info.plist",
      key: 'CFBundleVersion',
      value: version_info['build_number']
    )
    get_provisioning_profile  # invokes sigh
    build_app(workspace: "Connect.xcworkspace", scheme: "Connect")
  end
end

platform :ios do
  desc "Generate certificate and provisioning profile for distribution."
  lane :certs do
    get_certificates  # invokes cert
  end
end
