# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build a new beta release of the app."
  lane :beta do
    increment_build_number(xcodeproj: "Connect.xcodeproj")
    get_provisioning_profile  # invokes sigh
    build_app(workspace: "Connect.xcworkspace", scheme: "Connect")
  end
end

platform :ios do
  desc "Generate certificate and provisioning profile for distribution."
  lane :certs do
    get_certificates  # invokes cert
  end
end
