# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

def generate_version()
  package = load_json(json_path: '../package.json')
  app_version = package['version']
  build_number = DateTime.now.strftime('%Y%m%d%H%M')
  Hash[
    'app_version' => app_version,
    'build_number' => build_number
  ]
end

platform :android do
  desc 'Runs all the tests.'
  lane :test do
    gradle(task: 'test')
  end

  desc 'Create a new Beta build.'
  lane :beta do
    version_info = generate_version()
    gradle(
      task: 'clean assembleRelease',
      properties: {
        'versionCode': version_info['build_number'],
        'versionName': version_info['app_version']
      }
    )
  end

  desc 'Deploy a new version to the Google Play.'
  lane :deploy do
    gradle(task: 'clean assembleRelease')
    upload_to_play_store
  end
end
